# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/smartscale',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/smartscale',
                'lib_path': 'smartscale'},
  'syms': {'smartscale.core': {'smartscale.core.foo': ('core.html#foo', 'smartscale/core.py')}}}
